fsmkcamp19/urls.py
from webbrowser import register

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path

from fsmkcamp19.views import home, register, view_mail, me_in_camp, updatead
from fsmkcamp19.views import check_in, arrived, feedback, hacktivist_camp_view
from fsmkcamp19.views import dashboard, view_feedback


urlpatterns = [
    path('',home),
    path("register/",register),
    path("view_mail/",view_mail),
    path("me_in_camp/",me_in_camp),
    path("checkin/",check_in),
    path("arrived/",arrived),
    path("updatead/",updatead),
    path("feedback/",feedback),
    path("view_feedback/",feedback),
    path("ratatata/",view_feedback),
    path("hacktivist_camp/",hacktivist_camp_view),
    path('nimda/', admin.site.urls),
    path("dashboard/",dashboard),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fsmkcamp19/models.py
from django.contrib.auth.models import User
from django.db import models

from fsmkcamp19.utils import send_html_email

def get_first_name(self):
    return self.first_name

User.add_to_class("__str__", get_first_name)

gender_choices = (
    ("male","Male"),
    ("female","Female"),
    ("others","Others")
)

tshirt_choices = (
    ("S","Small"),
    ("M","Medium"),
    ("L","Large"),
    ("XL","X-Large"),
    ("XXL","2X-Large")
)

hacktivist_camp_choices = (
        ("can","I am attending the hacktivist camp"),
        ("interested","I am intersted but cant attend the camp"),
        ("iffree","I can contribute if at all I am free"),
        ("notinterested","Not interested")
    )


class Track(models.Model):
    track_name = models.CharField(max_length=300)
    track_description = models.TextField()
    track_seat_limit = models.PositiveIntegerField(default=100)
    track_seats_remaining = models.PositiveIntegerField(default=100)
    track_icon = models.TextField(default=None,blank=True,null=True)
    track_cost = models.PositiveIntegerField(default=2000)

    def __str__(self):
        return self.track_name

class Speakers(models.Model):
    name = models.CharField(max_length=200)
    designation = models.CharField(max_length=200)
    description = models.TextField()
    facebook = models.CharField(max_length=100,blank=True,null=True)
    twitter = models.CharField(max_length=100,blank=True,null=True)
    mastodon = models.CharField(max_length=100,blank=True,null=True)
    instagram = models.CharField(max_length=100,blank=True,null=True)
    profile_pic = models.ImageField(upload_to='speakers/')

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Camp Speaker"
class Colleges(models.Model):
    name = models.TextField()
    volunteer = models.ForeignKey(User, related_name="volunteer", on_delete = models.DO_NOTHING)
    coordinator = models.ForeignKey(User, related_name="coordinator", on_delete = models.DO_NOTHING)
    district = models.CharField(max_length = 100)


    def __str__(self):
        return self.name

        
class Registration(models.Model):

    name = models.CharField(max_length=200,help_text="Enter fullname as to be entered in certificate")
    gender = models.CharField(max_length=10,choices=gender_choices,default=gender_choices[1][0],help_text="Select your gender to allocate hostel rooms")
    college = models.ForeignKey(Colleges,on_delete=models.DO_NOTHING,default="Select college",help_text="Select your educational institute")
    track = models.ForeignKey(Track,on_delete=models.CASCADE)
    contact = models.PositiveIntegerField(help_text="Contact number for communication and updates")
    email = models.EmailField(help_text="Email for official communication")
    why = models.TextField(help_text="Why do you want to attend this camp. The helps us understand why you are interested and does not determine your registration")
    transaction_id = models.TextField(blank=True,null=True)
    is_payment_received = models.BooleanField(default=False)
    is_confirmed = models.BooleanField(default=False)
    arrival = models.DateTimeField(blank=True,null=True)
    departure = models.DateTimeField(blank=True,null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    tshirt = models.CharField(max_length = 10, choices = tshirt_choices, default=tshirt_choices[0][0], help_text = "T-Shirt size that fits you")
    is_payment_verified = models.BooleanField(default=False)
    is_confirmation_email = models.BooleanField(default=False)
    roomno = models.CharField(max_length=100,blank=True,null=True,default="unassigned")
    is_arrived = models.BooleanField(default=False)
    hacktivist_camp = models.CharField(max_length=100, choices=hacktivist_camp_choices,default="notinterested")
    track_cost_paid = models.PositiveIntegerField(default=None,null=True)

    class Meta:
        verbose_name = "Participant Registration"

class Volunteers(models.Model):
    name = models.CharField(max_length=200)
    college = models.ForeignKey(Colleges,on_delete=models.CASCADE)
    tshirt = models.CharField(max_length=20,choices=tshirt_choices)
    track = models.ForeignKey(Track,on_delete=models.CASCADE)
    email = models.EmailField()
    contact = models.PositiveIntegerField()
    gender = models.CharField(max_length=20,choices=gender_choices)
    roomno = models.CharField(max_length=100,blank=True,null=True,default="unassigned")
    is_arrived = models.BooleanField(default=False)
    hacktivist_camp = models.CharField(max_length=100, choices=hacktivist_camp_choices,default="notinterested")

    class Meta:
        verbose_name = "Track specific volunteer"

class FAQ(models.Model):
    question = models.CharField(max_length=500)
    answer = models.TextField()

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = "Website FAQ"

class Feedback(models.Model):
    feedback_choices = (
        ("iot","Internet of Things"),
        ("cc","Web Track"),
        ("ai","Data Science"),
        ("food","Food"),
        ("hostel","Hostel"),
        ("organising","Organising")
    )
    feedback = models.TextField()
    fcategory = models.CharField(max_length = 100, choices=feedback_choices)
    created_date = models.DateTimeField(auto_now_add=True)

class Testimonial(models.Model):
    person_name = models.CharField(max_length=200)
    statement = models.TextField()
    person_details = models.CharField(max_length=400)
    person_image = models.ImageField(upload_to="testimonials/",blank=True,null=True)

    class Meta:
        verbose_name = "Camp Testimonials"

    def __str__(self):
        return self.person_name

templates/checkin.html
<form action="/checkin/" method="POST">
    <input type="number" name="contact">
    {%csrf_token%}
    <button type="submit">Get details</button>
</form>

{%if participant%}

Name : {{participant.name}} <br>
College : {{participant.college}} <br>
Roomno : {{participant.roomno}} <br>
Type: {{ptype}}
<form action="/arrived/" method="post">
<input type="hidden" name="participant_id" value="{{participant.id}}">
<input type="hidden" name="ptype" value="{{ptype}}">
{%csrf_token%}
<button type="submit">Arrived</button>
</form>

{%endif%}

templates/dashboard.html
{%load bootstrap4%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <title>FSMKCamp'20</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css" >    
    <!-- DataTables -->
    <link rel="stylesheet" type="text/css" href="/static/css/datatables.min.css" >    


</head>
  <body class="container-fluid">
    <h2>
        Welcome {{user.firstname}},
    </h2>
    <br> <br>
    <div class="row">
        <div class="col-6">
            <h4>At this stage , out of the {{total_registered}} people who registered for the camp, about {{total_confirmed}} are confirmed and {{total_unconfirmed}} are yet to be confirmed. </h4>
        </div>
        <div class="col-6">
                <table class="table">
                    <thead>
                        <tr>
                            <td>Track Name</td>
                            <td>Confirmed Count</td>
                            <td>UnConfirmed Count</td>
                        </tr>
                    </thead>
                    <tbody>
                        {%for name, count in track_registered.items %}
                            <tr>
                                <td>
                                    {{name}}
                                </td>
                                <td>
                                    {{count.0}}
                                </td>
                                <td>
                                    {{count.1}}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
    </div>
    <br> <br>
    <div class="row">
        <div class="col-6">
            <h3>T-Shirt Size - Confirmed VS Non-Confirmed</h3>
            <table class='table'>
                <thead>
                    <tr>
                        <td>T-Shirt Size</td>
                        <td> Confirmed</td>
                        <td> Un-Confirmed</td>
                    </tr>
                </thead>
                <tbody>
                    {% for shirt_size,shirt_count in tshirt_sizes.items %} 
                        <tr>
                            <td>{{shirt_size}}</td>
                            <td>{{shirt_count.0}}</td>
                            <td>{{shirt_count.1}}</td>
                        </tr>    
                    {%endfor%}
                </tbody>
            </table>
        </div>

        <div class="col-6">
            <h3>Gender Distribution - Confirmed VS Non-Confirmed</h3>
            <table class='table'>
                <thead>
                    <tr>
                        <td>Gender</td>
                        <td> Confirmed</td>
                        <td> Un-Confirmed</td>
                    </tr>
                </thead>
                <tbody>
                    {% for gender,gender_count in gender_registered.items %} 
                        <tr>
                            <td>{{gender|title}}</td>
                            <td>{{gender_count.0|default:0}}</td>
                            <td>{{gender_count.1|default:0}}</td>
                        </tr>    
                    {%endfor%}
                </tbody>
            </table>
        </div>
        <div class="col-3">
            <h3>Educational Institutes I am tracking</h3>
            <table class='table' id="colleges_table">
                <thead>
                    <tr>
                        <td class="no-sort">College Name</td>
                        <td class="no-sort">Co-Ordinator</td>
                        <td class="no-sort">Volunteer</td>
                    </tr>
                </thead>
                <tbody>
                    {% for college in my_colleges %}
                        <tr>
                            <td>
                                {{college.name}}
                            </td>
                            <td>
                                {{college.volunteer}}
                            </td>
                            <td>
                                {{college.coordinator}}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col-9">
            <h3>Track specific participants under my name(sort by college name or track)</h3>
            <table class='table' id="participant_table">
                <thead>
                    <tr>
                        <td class="no-sort">Name</td>
                        <td> College Name </td>
                        <td class="no-sort"> Email</td>
                        <td class="no-sort"> Phone Number</td>
                        <td> Track</td>
                    </tr>
                </thead>
                <tbody>
                    {% for participant in my_participants%}
                    <tr>
                        <td>
                            {{participant.name}}
                        </td>
                        <td>
                            {{participant.college.name}}
                        </td>
                        <td>
                            {{participant.email}}
                        </td>
                        <td>
                            {{participant.contact}}
                        </td>
                        <td>
                            {{participant.track}}
                        </td>
                    </tr>
                        
                    {%endfor%}
                </tbody>
            </table>
        </div>
    </div>
</body>
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/datatables.min.js"></script>
<script>
    $('#participant_table').DataTable({
        "ordering": true,
        columnDefs: [{
          orderable: false,
          targets: "no-sort"
        }]
    });
</script>
</html>

templates/email_generic_template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>FSMK Camps'20 Registration confirmation</title>

    <meta name="description" content="Email confirmation for registration">
    <meta name="author" content="FSMK">

    <style>
        body {
            background-color: #f7f7f7;
        }
        
        .white {
            background-color: white !important;
        }
        .container{
            margin-left: 20%;
            margin-right: 20%;
            background-color: white;
        }
        .content{
            margin-left: 5%;
            margin-right: 5%;
        }
        
        .center {
            margin-left: 20vw;
        }
    </style>
</head>

<body>

    <div class="container">

        <div class="content">
                <img alt="FSMK Camp Logo" class="img-responsive" src="https://fsmkcamp19.sfo2.cdn.digitaloceanspaces.com/camp-logo-teal.png">
                <h3 class="center">
                    Welcome to FSMK Camps'20
                </h3>
                <p>
                    {% block email_header %}
                        Hi {{name}}, great to see you are interested in our camp. <br />
                        This year, the camp is happening from 25th - 31st January 2019 at Vemana Institute of Technology, Bangalore. <br />
                        FSMKCamps are residential in nature, and would require you to stay at the venue during the days of the camp. We will arrange for the stay in the college hostel itself, and take care of food during the days of the camp.
                    {% endblock %}
                </p>
            </div>

            <div class="content">
                {% block email_body %}

                {%endblock%}
            </div>

            <div class="content">
                <p>
                    You can also follow us on social media for public updates.

                    <br>

                    <a href="https://www.facebook.com/groups/freesoftwaremovementkarnataka/"><i class="fab fa-twitter fa-4x"></i> Facebook</a>
                    <a href="https://mastodon.social/@fsmk_org"><i class="fab fa-mastodon fa-4x"></i> Mastodon</a>
                    <a href="https://twitter.com/fsmk_org"><i class="fab fa-facebook fa-4x"></i> Twitter</a>
                    <a href="https://www.instagram.com/fsmk_org"><i class="fab fa-instagram fa-4x"></i> Instagram</a>
                </p>
            </div>
    </div>

</body>

</html>

templates/feedback.html
This is a generic feedback form and we dont track you here. Your feedback is completely anonymous unless you write your name etc. 
<form action="/feedback/" method="post">
    {{form.as_p}}
    {%csrf_token%}
    <button type="submit">Submit Feedback</button>
</form>

templates/foundya.html
We need this information to update the college about how many people are going to be arriving in the college hostel at what time and accordingly allocate spaces.

<form action="/updatead/" method="POST">
    {{adform}}
    {%csrf_token %}
    <input type="number" name="id" value="{{id}}" hidden="true">

    <button type="submit">Update</button>
</form>

templates/hacktivist_camp.html
Hacktivist camp is not for programmers. If fact there is alot of other ways to contribute. If you are creative enough, you could contribute to art work, if you a social media savvy person, you could help us manage our social media, if you are good at writing, you could write articles for us. There is just end for your skills to contribute here. 
<br>
<br>
Just come in, and help us save democracy :) 
<br>
<br>
<form action="/hacktivist_camp/" method="post">
        <input type="email" name="email" placeholder="Enter the email you used to register">
    <br>
    <br>
    {% csrf_token %}
        <input type="number" name="contact" placeholder="Enter the mobile number you entered to register">
    <br>
    <br>
    <button type="submit">Find me</button>
</form>
<br>
<br>
{%if participant%}

Hi {{participant.name}}, tell us your interest level


<form action="/hacktivist_camp/" method="post">
    {%csrf_token%}
    <input type="hidden" name="email" value="{{participant.email}}">
    <input type="hidden" name="contact" value="{{participant.contact}}">
    <select name="choice" id="">
        <option value="can">I can attend the camp </option>
        <option value="interested">I am intersted but cant attend the camp</option>
        <option value="iffree">I can contribute if at all I am free</option>
    </select>
    <button type="submit">Update my preference</button>
</form>

{%endif%}

{% if success %}

{{success}}

{%endif%}

templates/instructions.html
{% extends 'email_generic_template.html' %}

{% block email_header %}
{% endblock %}
{% block email_body %}
<br>
Please read this mail carefully and follow any instruction provided strictly!
<br>
<br>
______________________________________________________________________________________________________________________
<br>

Hello! 
<br>

Welcome aboard!
<br>

It's that time of the time where you pack your bags and attend the ever so successful FSMK Camp. We've been conducting camps for the past 6 years and we will continue to do so. If you're getting this mail, then you are participating. (Woo hoo!)
<br>

Free Software Movement Karnataka a.k.a FSMK has tied up with PES COLLEGE OF ENGINEERING, MANDYA this year - primarily because it will freshen you up away from the city tides. We can have the peace and fresh atmosphere in there which will be worth the distance you are traveling!
<br>

We've had a lot of fun and learned a lot in our previous camps. And we are sure, we will this time too. So, just relax, be yourself at the camp , and prepare to have a lot of fun! :)
<br>
<br>
______________________________________________________________________________________________________________________
<br>

Instructions:
<br>

1. First thing - Join the Whatsapp group immediately. All our interactions will primarily happen here : https://chat.whatsapp.com/IYThDNol5o164ddZKbim1N
  (Do not send this link to anyone else)
  <br>

2. Here is the general schedule of the camp : https://camp.fsmk.org/media/FSMK_camp_schedule_tentative.pdf
<br>

3. Here are the things to carry (Pen Drive is must! Do not forget) : https://gitlab.com/snippets/1798496
<br>

4. Here are the travel options for you to reach PESCE : https://gitlab.com/snippets/1798515
<br>

Since classes will start sharp at 9AM on 20th morning, we advice participants to reach Mandya by 19th night. Dinner will be provided on that night.
<br>

We want to be prepared to welcome you. So, kindly update your day of arrival in here: https://camp.fsmk.org/me_in_camp/
<br>

Upon reaching the college, contact one of the camp leads to assist you.
<br>

Camp Leads :
<br>

<br>
Girish : +91-9901430833
<br>

    Abhay : +91-76767 70004
<br>
<br>



5. Here is the code of conduct to be followed at the camp (kindly read and strictly follow this) : https://gitlab.com/snippets/1798505
<br>
<br>

______________________________________________________________________________________________________________________

<br>

For any further queries, do contact the FSMK Core Committe Members :
<br>
    Ram : +91-9916394958
    <br>
    Abhinav : +91-9894769833
    <br>
    Rizma : +91-960671293
    <br>
    <br>

Stay in touch with us by following us on
<br>

http://fsmk.org/
<br>

http://discuss.fsmk.org/
<br>

Official Social media accounts:
<br>

Mastodon: https://mastodon.social/@fsmk_org
<br>

Diaspora: https://diasp.in/u/fsmk_org
<br>

Twitter: http://twitter.com/fsmk_org
<br>

Instagram: https://www.instagram.com/fsmk_org/
<br>

Facebook Page: https://www.facebook.com/fsmkcamp/
<br>

Facebook Group: https://www.facebook.com/groups/freesoftwaremovementkarnataka/
<br>

{% endblock %}

templates/me_in_camp.html
<form action="." method="post">
    <input type="email" name="email" placeholder="Enter the email you used to register">
    <br>
    <br>
    {% csrf_token %}
    <input type="number" name="contact" placeholder="Enter the mobile number you entered to register">

    {%if not found%}

        <div style="color:red;"> You seem to entered a wrong email id or phone number </div>

    {%endif%}
    <br>
    <br>
    <button type="submit">Update my arrival and departure time</button>

</form>

templates/navbar.html
<header class="header navbar fixed-top navbar-expand-md">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img class="logo py-2" src="/static/img/campLogoWhite.png" alt="FSMK-logo"/>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#headernav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fas fa-bars text-align-right text-white"></span>
        </button>
        <div class="collapse navbar-collapse flex-sm-row-reverse" id="headernav">
            <ul class="nav navbar-nav menu">
                <li class="nav-item">
                    <a class="nav-link active" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="#speakers-section">Speakers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="#tracks-section">Tracks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="#faq">FAQ</a>
                </li>                  
                <!-- <li class="nav-item">
                    <a class="nav-link " href="#">Schedule & Syllabus </a>
                </li> -->
                <!-- <li class="nav-item">
                    <a class="nav-link " href="#">Contact</a>
                </li> -->
            </ul>
        </div>
    </div>
</header>

templates/register_confirm.html
{% extends 'email_generic_template.html' %}

{% block email_header %}
   
{% endblock %}
{% block email_body %}
Hi {{name}}, we are writing to you with a confirmation for your registration  <br />
for FSMKCamps'20, happening from 25th - 31st January 2020 at Vemana Institute of Technology, Bangalore <br /><br />
FSMKCamps are residential in nature, and would require you to stay at the venue during the days of the camp. 
We will arrange for the stay in the college hostel itself, and take care of food during the days of the camp.
<hr>
Below are the details of your registration : <br />

Amount Received : {{fee}} /- INR <br>
Transaction id  : {{transaction_id}} <br>
Track           : {{track}} <br>
T-Shirt         : {{tshirt}} <br>
College         : {{college}} <br>
Person who paid : {{volunteer.first_name}} or {{coordinator.first_name}} <br>
<br>
<br>
We will keep you posted of further updates. Keep checking your emails regularly. 
{% endblock %}

templates/register_reminder.html
{% extends 'email_generic_template.html' %}

{% block email_header %}
  
{% endblock %}
{% block email_body %}
Hello {{name}},

It is quite exciting for us to see that you are interested in FSMKCamp'20 . But it appears that you are yet to complete your payment to confirm your seat. We highly encourage you to confirm your seat soon, as there are limited seats available and seats are filling up fast. 

We are sharing the contact details below. Please contact one of them at the earliest for payment and confirmation.

Below are the details of your registration : <br />
<br>
<br>
Amount to be paid : {{fee}} /- INR <br>
Track             : {{track}} <br>
T-Shirt           : {{tshirt}} <br>
College           : {{college}} <br>
<br>
<br>
Point of Contact to make the payment 
<br>
<br>
<table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Contact</th>
                <th scope="col">Email</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>{{volunteer.first_name}}</td>
                <td>{{volunteer.username}}</td>
                <td>{{volunteer.email}}</td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>{{coordinator.first_name}}</td>
                <td>{{coordinator.username}}</td>
                <td>{{coordinator.email}}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}

templates/register_success.html
{% extends 'email_generic_template.html' %}

{% block email_header %}
    Hi {{name}}, Thank you for registring for FSMKCamps'20 <br />
    This year, the camp is happening from 25th - 31st January 2020 at Vemana Institute of Technology, Bangalore. <br />
    FSMKCamps are residential in nature, and would require you to stay at the venue during the days of the camp. We will arrange for the stay in the college hostel itself, and take care of food during the days of the camp.
{% endblock %}

{% block email_body %}
    <div class="">
        <div class="content">
            <h2>
                1. Camp registration Fee
            </h2>
            <p>
                The registration fee for <strong>"{{track}}"</strong> is <strong>{{fee}} /- INR </strong>. 
                <br>
                The fee includes track specific kits (if any), food and stay during the days of the camp, one T-shirt ({{tshirt}}).
                We also use the funds from this fee to pay for the stay and food of our volunteers and
                speakers, and also to pay the travel and other allowances of the speakers.
            </p>
            <p>OR</p>
            <p>Make payment with below details</p>
            <p>Name: Free Software Movement Karnataka<br>
            SB Account No: 1172101012320<br>
            IFSC code :  CNRB0001172 <br>
            Bank:  Canara Bank, Kalasipalya. Bangalore</p>
            <p>
                To pay the camp fee you can contact any of the "Point of Contact" shared below. <br />
                <strong> Note: </strong> Unless the payment is made and a confirmation is received, this mail does not confirm your registration in the camp.
            </p>
        </div>
    </div>

    <hr>

    <div class="">
        <div class="content">
            <h2>
                2. Point of Contact
            </h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Contact</th>
                        <th scope="col">Email</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>{{volunteer.first_name}}</td>
                        <td>{{volunteer.username}}</td>
                        <td>{{volunteer.email}}</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>{{coordinator.first_name}}</td>
                        <td>{{coordinator.username}}</td>
                        <td>{{coordinator.email}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <hr>
    <div class="">
        <div class="content">
            <h2>
                3. What next?
            </h2>
            <p>
                Once we have received your payment, we will send you the ticket of confirmation containing
                further details. Give us one day time to confirm payment, since we have to do the payment verfication
                manually at this point. FSMK camps are not the usual workshops that you see around. We try to give life to
                exploring technology. We will also put you in touch with the speakers, add you to our public groups where you can
                meet more like-minded people like yourself, hangout with a lot more of us.
            </p>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">

            <button type="button" class="btn btn-block btn-success btn-lg">
                Great to see your interest in our camps {{name}} :)
            </button>
        </div>
    </div>

{% endblock %}

templates/view_feedback.html
{%load bootstrap4%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <title>FSMKCamp'20</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css" >    
    <link rel="stylesheet" type="text/css" href="/static/css/dataTables.bootstrap4.min.css" >    

  </head>
  <body class="container">

    <div class="container-fluid">
        <table id="feedback"  class="table table-striped table-bordered"  cellspacing="0" width="100%">
            <thead>
                <tr id="filters">
                    <th scope="col"></th>
                    <th scope="col">Feedback</th>
                    <th scope="col">Category</th>
                    <th scope="col">Date</th>
                </tr>
            </thead>
            <tbody>
                {% for feedback in feedbacks %}
                    <tr>
                        <td><a href="#{{feedback.id}}" id="{{feedback.id}}">{{feedback.id}}</a></td>
                        <td>{{feedback.feedback}}</td>
                        <td>{{feedback.get_fcategory_display}}</td>
                        <td>{{feedback.created_date|date:"D d M"}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>    
    </div>
</body>

<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/datatables.min.js"></script>

<script>
    $(document).ready( function () {
        $('#feedback').DataTable({  // Reinitialize data table
            responsive: true,
            lengthMenu: [[-1, 10, 25, 50], ["All",10, 25, 50]],
            order: [],
            columnDefs: [ { orderable: false, targets: [0,1] } ],            
        });
    } );
</script>
</html>